/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package theOnlyHouseICanAfford;

import java.awt.Graphics;

/**
 *
 * @author mspriggs
 */
public class MyHome extends javax.swing.JPanel {

    /**
     * Creates new form MyHome
     */
    public MyHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawRect(50, 100, 100, 100); // Draw a simple square to represent the house
        g.drawPolygon(new int[] { 50, 100, 150 }, new int[] { 100, 50, 100 }, 3); // Draw a triangle roof
        g.drawRect(60, 110, 25, 25); // Draw a window
        g.drawArc(110, 107, 30, 30, 0, 360); // Draw a circle window
        // g.drawRoundRect(90, 150, 20, 50, 100, 20); // Draw a door
        g.drawLine(90, 200, 90, 165); // Left side of door
        g.drawLine(110, 200, 110, 165); // Right side of door
        g.drawArc(90, 150, 20, 30, 0, 180); // Top of door

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
