/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import model.Student;

import javax.swing.JOptionPane;

import database.StudentDatabase;

/**
 *
 * @author mspriggs
 */
public class displayForm extends javax.swing.JPanel {

    /**
     * Creates new form displayForm
     */
    public displayForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentDisplayDiv = new javax.swing.JPanel();
        fullNameLabelDisplay = new javax.swing.JLabel();
        fullNameLabelEntry = new javax.swing.JTextField();
        gradeDisplay = new javax.swing.JTextField();
        gradeLabelDisplay = new javax.swing.JLabel();
        displayGradeButton = new javax.swing.JButton();
        modifyGradeButton = new javax.swing.JButton();
        deleteGradeButton = new javax.swing.JButton();

        studentDisplayDiv.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Display Grade:",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        fullNameLabelDisplay.setText("Student Name:");

        gradeDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeDisplayActionPerformed(evt);
            }
        });

        gradeLabelDisplay.setText("Grade:");

        displayGradeButton.setText("Display Grade");
        displayGradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayGradeButtonActionPerformed(evt);
            }
        });

        modifyGradeButton.setText("Modify Grade");

        deleteGradeButton.setText("Delete Grade");

        javax.swing.GroupLayout studentDisplayDivLayout = new javax.swing.GroupLayout(studentDisplayDiv);
        studentDisplayDiv.setLayout(studentDisplayDivLayout);
        studentDisplayDivLayout.setHorizontalGroup(
                studentDisplayDivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentDisplayDivLayout
                                .createSequentialGroup()
                                .addContainerGap(20, Short.MAX_VALUE)
                                .addGroup(studentDisplayDivLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(studentDisplayDivLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(studentDisplayDivLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fullNameLabelDisplay)
                                                        .addComponent(gradeLabelDisplay))
                                                .addGap(18, 18, 18)
                                                .addGroup(studentDisplayDivLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(fullNameLabelEntry,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 155,
                                                                Short.MAX_VALUE)
                                                        .addComponent(gradeDisplay)))
                                        .addGroup(studentDisplayDivLayout.createSequentialGroup()
                                                .addComponent(displayGradeButton,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 114,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(modifyGradeButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(deleteGradeButton)))
                                .addGap(16, 16, 16)));
        studentDisplayDivLayout.setVerticalGroup(
                studentDisplayDivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentDisplayDivLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(studentDisplayDivLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fullNameLabelDisplay)
                                        .addComponent(fullNameLabelEntry, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(studentDisplayDivLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gradeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gradeLabelDisplay))
                                .addGap(18, 18, 18)
                                .addGroup(studentDisplayDivLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(displayGradeButton)
                                        .addComponent(modifyGradeButton)
                                        .addComponent(deleteGradeButton))
                                .addContainerGap(15, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(studentDisplayDiv, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(studentDisplayDiv, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(115, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void gradeDisplayActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gradeDisplayActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_gradeDisplayActionPerformed

    private void displayGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_displayGradeButtonActionPerformed

        // Get full name from text field
        String fullName = fullNameLabelEntry.getText();

        // Retrieve student from database

        Student student = StudentDatabase.getStudent(fullName);
        if (student != null) {
            // Dispay grade in gradeDisplay
            String grade = student.getGrade();
            gradeDisplay.setText(grade);

        } else {
            // Show error message
            System.out.println("Student " + fullName + " not found in database.");
            JOptionPane.showMessageDialog(this, "Student " + fullName + " not found in database.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_displayGradeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteGradeButton;
    private javax.swing.JButton displayGradeButton;
    private javax.swing.JLabel fullNameLabelDisplay;
    private javax.swing.JTextField fullNameLabelEntry;
    private javax.swing.JTextField gradeDisplay;
    private javax.swing.JLabel gradeLabelDisplay;
    private javax.swing.JButton modifyGradeButton;
    private javax.swing.JPanel studentDisplayDiv;
    // End of variables declaration//GEN-END:variables
}
