/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import model.Student;

/**
 *
 * @author mspriggs
 */
public class entryForm extends javax.swing.JPanel {

    /**
     * Creates new form entryForm
     */
    public entryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentEntryDiv = new javax.swing.JPanel();
        firstNameLabelEntry = new javax.swing.JLabel();
        lastNameLabelEntry = new javax.swing.JLabel();
        firstNameEntry = new javax.swing.JTextField();
        lastNameEntry = new javax.swing.JTextField();
        entryStudentSubmitButton = new javax.swing.JButton();
        gradeLabelEntry = new javax.swing.JLabel();
        gradeEntry = new javax.swing.JTextField();

        studentEntryDiv.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Student Grades:",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        firstNameLabelEntry.setText("First Name:");

        lastNameLabelEntry.setText("Last Name:");

        entryStudentSubmitButton.setText("Store");
        entryStudentSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryStudentSubmitButtonActionPerformed(evt);
            }
        });

        gradeLabelEntry.setText("Grade:");

        gradeEntry.setToolTipText("");

        javax.swing.GroupLayout studentEntryDivLayout = new javax.swing.GroupLayout(studentEntryDiv);
        studentEntryDiv.setLayout(studentEntryDivLayout);
        studentEntryDivLayout.setHorizontalGroup(
                studentEntryDivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentEntryDivLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(studentEntryDivLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstNameLabelEntry)
                                        .addComponent(lastNameLabelEntry)
                                        .addComponent(gradeLabelEntry))
                                .addGap(36, 36, 36)
                                .addGroup(studentEntryDivLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(firstNameEntry)
                                        .addComponent(lastNameEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 212,
                                                Short.MAX_VALUE)
                                        .addGroup(studentEntryDivLayout.createSequentialGroup()
                                                .addComponent(gradeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(entryStudentSubmitButton)))
                                .addContainerGap(47, Short.MAX_VALUE)));
        studentEntryDivLayout.setVerticalGroup(
                studentEntryDivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentEntryDivLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(studentEntryDivLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstNameLabelEntry)
                                        .addComponent(firstNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(studentEntryDivLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastNameLabelEntry)
                                        .addComponent(lastNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(studentEntryDivLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(gradeLabelEntry)
                                        .addGroup(studentEntryDivLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(gradeEntry, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(entryStudentSubmitButton)))
                                .addContainerGap(37, Short.MAX_VALUE)));

        firstNameLabelEntry.getAccessibleContext().setAccessibleName("");
        firstNameLabelEntry.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(studentEntryDiv, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(40, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(studentEntryDiv, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void entryStudentSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_entryStudentSubmitButtonActionPerformed
        // TODO add your handling code here:
        // Make instance of Class Student
        String firstName = firstNameEntry.getText();
        String lastName = lastNameEntry.getText();
        String grade = gradeEntry.getText();

        Student student = new Student(firstName, lastName, grade);

        System.out.println("Total Students: " + Student.getTotalStudents());

        // Clear text fields after submission
        firstNameEntry.setText("");
        lastNameEntry.setText("");

    }// GEN-LAST:event_entryStudentSubmitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entryStudentSubmitButton;
    private javax.swing.JTextField firstNameEntry;
    private javax.swing.JLabel firstNameLabelEntry;
    private javax.swing.JTextField gradeEntry;
    private javax.swing.JLabel gradeLabelEntry;
    private javax.swing.JTextField lastNameEntry;
    private javax.swing.JLabel lastNameLabelEntry;
    private javax.swing.JPanel studentEntryDiv;
    // End of variables declaration//GEN-END:variables
}
